### ISSUE TITLE
Evaluate the use of the surround parameters 

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#12]
We need to determine the usefulness of the surround and similar parameters to determine if they give us any useful ways to model dim, dark environments etc

**Comment by KevinJW** [comment]
We should start evaluation based on dim in and out as the base settings.

**Comment by nick-shaw** [comment]
My experiments suggest we could just apply a suitable gamma to J and multiplier to M after tone mapping, rather than going back and forth through the model multiple times.

But we also have the question of whether we should have a dark to dim modification at all. Josh and his colourists are of the opinion that there should be none, so the result is the same as a colorimetric conversion between Rec.709 and P3 2.6 gamma.

**Comment by scottdyer** [comment]
None of the transforms are set to use the dark-to-dim modification by default, but there is a module included which will slightly modify the gamma of the output if the value is changed. This needs more investigation to verify the magnitude of those changes, but the mechanism is present.
