### ISSUE TITLE
When viewing plots on the Mh scope a small hook is visible near neutral

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#4]
As shown in the 16/11/2022 meeting plotting constant hue lines near neutral has a slight hook/kink. May be related to #3

**Comment by priikone** [comment]
This may be a clipping that happens when in SDR it hits display white (128 in linear).  This wasn't visible with the older tonescale since it hit display white at max ACES.  I only see this in Hellwig.  I assume this is when the M component collapses to 0.  Following is ramp with ACES whitepoint shifted to DCI whitepoint and given as input to the DRT (v24).

![dciramp_v24_Hellwig](https://user-images.githubusercontent.com/7447241/203393837-5104b38e-324e-46c0-b028-89f736245cd1.png)

**Comment by KevinJW** [comment]
related to the discount_illuminant issue in #3
